FROM continuumio/miniconda3
USER root

ENV TRANSFORMERS_OFFLINE 1

WORKDIR /app

# miniconda install
RUN conda install -c conda-forge transformers

COPY hugging_face_sentiment_test/resources /app/hugging_face_sentiment_test/resources
COPY hugging_face_sentiment_test/test_models.py /app/hugging_face_sentiment_test

ENV PYTHONPATH /app

CMD python hugging_face_sentiment_test/test_models.py