FROM huggingface/transformers-pytorch-gpu:4.23.1

USER root

ENV TRANSFORMERS_OFFLINE 1

WORKDIR /app

RUN pip install pandas

COPY hugging_face_sentiment_test/resources /app/hugging_face_sentiment_test/resources
COPY hugging_face_sentiment_test/test_models.py /app/hugging_face_sentiment_test

ENV PYTHONPATH /app

CMD python3 hugging_face_sentiment_test/test_models.py