FROM huggingface/transformers-tensorflow-gpu:4.25.1

USER root

ENV TRANSFORMERS_OFFLINE 1

WORKDIR /app

RUN pip install pandas

COPY hugging_face_sentiment_test/resources /app/hugging_face_sentiment_test/resources
COPY hugging_face_sentiment_test/model_benchmark.py /app/hugging_face_sentiment_test

ENV PYTHONPATH /app

CMD python3 hugging_face_sentiment_test/model_benchmark.py